### ISSUE TITLE
不知道如何调用翻译函数

### ISSUE THREAD

**Issue by lq2644134516** [nszy007/CN_Nessus_Plugins_Interface#2]
您好，我使用python直接运行脚本后没有自动创建config.yml配置文件，甚至我也不清楚如何调用翻译函数，我看了您的自诉文档还是一脸懵逼，可以请您指导指导我吗

**Comment by nszy007** [comment]
根据自己的操作系统下载release下面的二进制文件运行，就会创建一个查询接口服务。
python代码只是用了调用接口的demo，方便大家自己根据需求修改。
